# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :update_podspec do
    version_bump_podspec(path: "#{ENV['BITRISE_DEPLOY_DIR']}/github-repo/drivekit-ui-frameworks/DriveKitDriverDataUI.podspec", version_number: "#{ENV['BITRISE_GIT_TAG']}")
  end
end
