# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"
  lane :update_podspec do |values|
    version = values[:pod_version]
    version_bump_podspec(path: "DriveKitCommonUI.podspec", version_number: "#{version}")
    version_bump_podspec(path: "DriveKitDriverDataUI.podspec", version_number: "#{version}")
    version_bump_podspec(path: "DriveKitDriverAchievementUI.podspec", version_number: "#{version}")
    version_bump_podspec(path: "DriveKitVehicleUI.podspec", version_number: "#{version}")
    version_bump_podspec(path: "DriveKitPermissionsUtilsUI.podspec", version_number: "#{version}")
    version_bump_podspec(path: "DriveKitChallengeUI.podspec", version_number: "#{version}")
  end
end
